title: Stephanie Mills
author:
  name: Stephanie Mills
url: https://smillswriter.com
imagePath: /resources/images
permalink: /:categories/:title/
exclude: [vendor, Gemfile, Gemfile.lock]
timezone: America/Detroit
markdown: kramdown
kramdown:
  auto_ids: false
  parse_block_html: true
sass:
  sass_dir: resources/_scss
  style: :compressed
defaults:
  -
    scope:
      path: "_posts/books"
      type: "posts"
    values:
      layout: "page"
      variant: "post"
      category: "books"
  -
    scope:
      path: "_posts/essays"
      type: "posts"
    values:
      layout: "page"
      variant: "essay"
      category: "essays-talks"
      permalink: /preview-020200525/:categories/:title/
