title: Stephanie Mills
author:
  name: Stephanie Mills
url: http://smillswriter.com
imagePath: /resources/images
permalink: /:categories/:title/
exclude: [vendor, Gemfile, Gemfile.lock]
timezone: America/Detroit
markdown: kramdown
kramdown:
  auto_ids: false
sass:
  sass_dir: resources/_scss
  style: :compressed
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "page"
      variant: "post"
      category: "books"
